import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export const metadata = { title: "Terms of Service — JPForms" };

export default function Terms() {
  return (
    <div className="mx-auto max-w-3xl space-y-6">
      <h1 className="text-2xl font-bold">Terms of Service & Disclaimer</h1>
      <Card>
        <CardHeader><CardTitle>1. Nature of the Software</CardTitle></CardHeader>
        <CardContent className="text-sm leading-relaxed">
          JPForms provides software translation utilities that help users understand
          and self-complete Japanese administrative forms. The service is provided
          for <strong>informational self-application purposes only</strong>. Using the
          software does not create an attorney–client, scrivener–client, or any other
          professional relationship.
        </CardContent>
      </Card>
      <Card>
        <CardHeader><CardTitle>2. Legal Representation Disclaimer</CardTitle></CardHeader>
        <CardContent className="text-sm leading-relaxed">
          Official legal representation, agency filing (代理申請), and legal document
          review are <strong>not</strong> performed by the software. Where such
          services are requested and eligible, they are dispatched directly to our
          certified partner scrivener office (licensed Gyoseishoshi / Shiho-shoshi),
          with whom a separate engagement is formed. Translations generated by the
          platform are machine-assisted and may contain errors; users are solely
          responsible for verifying accuracy before submitting documents to any
          government office.
        </CardContent>
      </Card>
      <Card>
        <CardHeader><CardTitle>3. Limitation of Liability</CardTitle></CardHeader>
        <CardContent className="text-sm leading-relaxed">
          To the maximum extent permitted by law, JPForms shall not be liable for any
          damages arising from rejection of submitted documents, immigration or
          administrative decisions, translation errors, or reliance on chatbot
          responses. The service is provided &quot;as is&quot; without warranties of
          any kind.
        </CardContent>
      </Card>
      <Card>
        <CardHeader><CardTitle>4. User Obligations</CardTitle></CardHeader>
        <CardContent className="text-sm leading-relaxed">
          Users must provide accurate information, must not use the service to prepare
          fraudulent or misleading documents, and must not resell or redistribute the
          generated materials as a competing translation service.
        </CardContent>
      </Card>
    </div>
  );
}
